# Generated by Django 4.0.8 on 2022-12-26 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lifecycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('owner_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Lifecycle',
                'verbose_name_plural': 'Lifecycles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lifecycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifecycles.lifecycle')),
            ],
            options={
                'verbose_name': 'Lifecycle Stage',
                'verbose_name_plural': 'Lifecycle Stages',
                'ordering': ['-created_at'],
            },
        ),
    ]
