# Generated by Django 4.0.8 on 2022-12-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifecyclestage',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lifecyclestage',
            name='roles',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='owner', max_length=255),
        ),
    ]
