# Generated by Django 4.0.8 on 2022-12-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('lifecycles', '0002_lifecyclestage_order_number_lifecyclestage_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifecycle',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='lifecycle',
            name='owner_type',
        ),
        migrations.AddField(
            model_name='lifecycle',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lifecycles', to='organisations.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lifecycle',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lifecycle',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
