# Generated by Django 4.0.8 on 2022-12-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycles', '0003_remove_lifecycle_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecyclestage',
            name='lifecycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='lifecycles.lifecycle'),
        ),
    ]
