# Generated by Django 4.0.8 on 2022-12-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner_type',
            field=models.ForeignKey(limit_choices_to=(('user', 'User'), ('team', 'Team'), ('organization', 'Organization')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
