# Generated by Django 4.0.8 on 2022-12-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0004_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('model__in', ['user', 'team'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
