# Generated by Django 4.0.8 on 2022-12-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organizationmember_role'),
        ('projects', '0005_alter_project_owner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner_type',
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organisations.organization'),
            preserve_default=False,
        ),
    ]
