# Generated by Django 4.0.8 on 2022-12-27 09:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
        ('lifecycles', '0003_remove_lifecycle_owner_id_and_more'),
        ('projects', '0005_alter_project_owner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlregisters', to='experiments.experiment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='MLRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mlregister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mldeployments', to='mlregister.mlregister')),
            ],
        ),
        migrations.CreateModel(
            name='MLDeploymentLifecycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lifecycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycles', to='lifecycles.lifecycle')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='mlregister.mlrelease')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='lifecycles.lifecyclestage')),
            ],
        ),
    ]
