# Generated by Django 4.0.8 on 2022-12-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlregister', '0004_mlregister_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlrelease',
            name='stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
