# Generated by Django 4.0.8 on 2022-12-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlregister', '0005_mlrelease_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlrelease',
            name='name',
        ),
        migrations.AddField(
            model_name='mlrelease',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
