# Generated by Django 4.0.8 on 2022-12-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlregister', '0006_remove_mlrelease_name_mlrelease_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlrelease',
            name='mlregister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='mlregister.mlregister'),
        ),
    ]
